services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - TAWAKTO_PROPERTY_ID=663e222a07f59932ab3e35cc
      - TAWAKTO_WIDGET_ID=1hthbaum8
      - AUTH_SECRET=xMkJaZKzK36EM6W19uqt6WUUnu1+4S3hmYO5GpvQpXvq
      - NEXTAUTH_URL=https://www.wafipix.com
      - JWT_SECRET=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
      - GOOGLE_CLIENT_ID=436253371960-faltkh2kfps1q7fgjtgtd1q5b0ikaq64.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - EMAIL_USER=info.alamgirhussain@gmail.com
      - EMAIL_PASS=bmtkyzhpcdhrhbuq
     
    depends_on:
      - server

    develop:
      watch: 
        - action: rebuild
          path: ./client/package.json

        - action: sync
          path: ./client/
          target: /app

    networks:
      - wafipix_network
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile

    ports:
      - 3001:3001

    environment:
      - PORT=3001
      - MONGODB_URL=mongodb+srv://wafipix1:Openit420@wafipixcluster.lm4udbf.mongodb.net/wafipix?retryWrites=true&w=majority&appName=wafipixCluster
      - CLOUDINARY_CLOUD_NAME=dugc533jq
      - CLOUDINARY_API_KEY=911967824621894
      - CLOUDINARY_API_SECRET=EBzOzyWl2UfNguHh9CGqxfC4U2k
      - CLOUDINARY_PORTFOLIO_PROFILE_IMAGE_FOLDER=wafipix/portfolio/images/profile
      - CLOUDINARY_PORTFOLIO_MEDIA_IMAGE_FOLDER=wafipix/portfolio/images/media
      - CLOUDINARY_PORTFOLIO_MEDIA_VIDEO_FOLDER=wafipix/portfolio/videos/media
      - JWT_SECRET=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
      - EMAIL_USER=info.alamgirhussain@gmail.com
      - EMAIL_PASS=cbyl fmrs lifc agbt
      - CONTACT_MAIL=info.alamgirhussain@gmail.com

    develop:
      watch: 
        - action: rebuild
          path: ./server/package.json

        - action: sync
          path: ./server/src
          target: /app
    
    networks:
      - wafipix_network

networks:
  wafipix_network:
    driver: bridge

  

