services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - SERVER_BASE_URL=${SERVER_BASE_URL}

      #nextauth url
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - AUTH_SECRET=${AUTH_SECRET}

      #google console
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

    depends_on:
      - server


    networks:
      - wafipix_network
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile

    ports:
      - 3001:3001

    environment:
      - PORT=3001
      - ORIGIN=${ORIGIN}
      - MONGODB_URL=${MONGODB_URL}
      - CLOUDINARY_CLOUD_NAME=${CLOUDINARY_CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUDINARY_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUDINARY_API_SECRET}
      - CLOUDINARY_PORTFOLIO_PROFILE_IMAGE_FOLDER=${CLOUDINARY_PORTFOLIO_PROFILE_IMAGE_FOLDER}
      - CLOUDINARY_PORTFOLIO_MEDIA_IMAGE_FOLDER=${CLOUDINARY_PORTFOLIO_MEDIA_IMAGE_FOLDER}
      - CLOUDINARY_PORTFOLIO_MEDIA_VIDEO_FOLDER=${CLOUDINARY_PORTFOLIO_MEDIA_VIDEO_FOLDER}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - CONTACT_MAIL=${CONTACT_MAIL}

    networks:
      - wafipix_network


  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongodb_data:/data/db
    networks:
      - wafipix_network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://root:admin@mongo:27017/
      ME_CONFIG_BASICAUTH: false

    depends_on:
      - mongo
    networks:
      - wafipix_network

volumes:
  mongodb_data:

networks:
  wafipix_network:
    driver: bridge

  

